version: "2"
services:
#  config-server:
#    image: httpd:alpine
#    ports:
#      - "8000:80"
#    volumes:
#      - ${DIR}/config-server:/usr/local/apache2/htdocs:ro
  postgres:
    image: starefossen/pgrouting:9.6-2.3-2.3
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
  mongo:
    image: mongo:3.4
    expose:
      - "27017"
  keycloak-server:
    image: jboss/keycloak-postgres:latest
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  redis:
    image: redis:latest
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    image: logstash:latest
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
              output { elasticsearch { hosts => ["elasticsearch"] } }'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
      - logstash
    depends_on:
      - logstash