version: "2"
services:
#  config-server:
#    image: httpd:alpine
#    ports:
#      - "8000:80"
#    volumes:
#      - ${DIR}/config-server:/usr/local/apache2/htdocs:ro
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: 'test:1:1:compact'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: ithings/nemesis/postgres:latest
    build:
      context: ./postgresql
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nemesis
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_DB: keycloak
  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
  keycloak:
    image: ithings/nemesis/keycloak:latest
    build:
      context: ./keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=nemesis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    image: logstash:latest
    container_name: logstash
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
              output { elasticsearch { hosts => ["elasticsearch"] } }'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:latest
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
      - logstash
    depends_on:
      - logstash